# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.adaptspec <- function(nLoop, nWarmUp, xR, priorList, probMM1, nSegmentsStart = 1L, showProgress = FALSE) {
    .Call('BayesSpec_adaptspec', PACKAGE = 'BayesSpec', nLoop, nWarmUp, xR, priorList, probMM1, nSegmentsStart, showProgress)
}

.get_sample_default <- function(xR, priorList, nStartingSegments) {
    .Call('BayesSpec_getSampleDefault', PACKAGE = 'BayesSpec', xR, priorList, nStartingSegments)
}

.get_sample_filled <- function(xR, priorList, stateList) {
    .Call('BayesSpec_getSampleFilled', PACKAGE = 'BayesSpec', xR, priorList, stateList)
}

.get_metropolis_log_ratio <- function(currentR, proposalR, xR, priorList) {
    .Call('BayesSpec_getMetropolisLogRatio', PACKAGE = 'BayesSpec', currentR, proposalR, xR, priorList)
}

.independent_mixture <- function(nLoop, nWarmUp, xR, priorsR, weightsPriorR, probMM1, showProgress = FALSE) {
    .Call('BayesSpec_independentMixture', PACKAGE = 'BayesSpec', nLoop, nWarmUp, xR, priorsR, weightsPriorR, probMM1, showProgress)
}

splines_basis1d <- function(xR, nBases, omitLinear = FALSE) {
    .Call('BayesSpec_splineBasis1dR', PACKAGE = 'BayesSpec', xR, nBases, omitLinear)
}

